# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'gome' do
  use_frameworks!

#  pod 'Socket.IO-Client-Swift'

  target 'gomeTests' do
    inherit! :search_paths
  end

  target 'gomeUITests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end

end
